database:
  ==: dev.drekamor.warp.database.DatabaseCredentials
  database: database
  username: user
  password: password
  host: host
  port: 3609
  poolSize: 10
  idleTimeout: 86400
  connectionTimeout: 86400
  maxLifetime: 86400
